# Generated by Django 6.0.1 on 2026-01-29 06:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="interest",
            old_name="to_user",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="interest",
            old_name="from_user",
            new_name="sender",
        ),
        migrations.AlterUniqueTogether(
            name="interest",
            unique_together={("sender", "receiver")},
        ),
    ]
